### ISSUE TITLE
Discussion jQuery collapse

### ISSUE THREAD

**Issue by andersrehn** [helsingborg-stad/modularity-form-builder#8]
I was wondering if the logic for the collapse form JavaScript code works as intended?
Referring to https://github.com/helsingborg-stad/modularity-form-builder/blob/master/source/js/front/collapse.js#L23

```
   Collapse.prototype.handleEvents = function () {
        $('button', '.mod-form-collapse').click(function(e) {
            e.preventDefault();

            $('.mod-form-collapse__icon > i', e.target).toggleClass('pricon-plus-o pricon-minus-o');

            $(e.target).parents('.mod-form-collapse')
                .nextUntil(':not(.mod-form-field)')
                .each(function() {
                    $(this).fadeToggle('fast');
                });

        }.bind(this));
    };
```

The idea here is that you add a collapse field in wp-admin for your form. According to the instructions as an editor it says that this is a layout block until the next layout-block exists.

If jQuery selects the parent of the pressed button `$(e.target).parents('.mod-form-collapse')` this will be a div and the siblings in the `HTML dom` will be `<div class="grid">..</div>` the stop condition will be a `<div class="grid mod-form-field">..</div>`

If we do `.nextUntil(':not(.mod-form-field)')` that will stop at the first  `<div class="grid">..</div>` and not at `<div class="grid mod-form-field">..</div>` in which I believe is where we are supposed to stop. 

Is it not preferred to change from `.nextUntil(':not(.mod-form-field)')` to `.nextUntil('.mod-form-field')`?

**Comment by jonatanhanson** [comment]
The idea was to create an accordion effect, so that _all_ input fields(except if it's another collapse field) that are placed after the button in the Dom will be hidden until we click it.

I agree it may not be very obvious how the code works, but it works as intended. If we would target `.nextUntil('.mod-form-field')` it stops immediately and nothing would be selected. Atleast when I tested it.
